#! /bin/sh

flags=-static

#
# if there is a shared musl library don't set -static as default
#
if [ -f "$0/../../lib/libc.so" -o -f "$0/../../lib/libc.dylib" ]
then
   flags=
fi

exec musl-gcc ${flags} "$@"
